[package]
name = "gensim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy-inspector-egui = "0.23.4"
bevy_rapier3d = "0.25.0"
bevy_third_person_camera = "0.1.5"
rand = "0.8.5"
rand_distr = "0.4.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
